<?php

namespace SfingeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PrioritaProceduraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrioritaProceduraRepository extends EntityRepository
{
}
