services:
    pagina_listener:
        class: PaginaBundle\EventListener\PaginaListener
        tags: [{name: kernel.event_listener, event: kernel.controller, method: onKernelController}]
        arguments: ['@annotation_reader', '@twig', '@router']
        
    pagina:
        class: PaginaBundle\Services\Pagina
        arguments: ['@twig']    