select rich.id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 803589 UNION 
select rich.id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 800535 UNION 
select rich.id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 802065 UNION 
select rich.id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 802298 UNION 
select rich.id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 794599 UNION 
select rich.id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 803462 UNION 
select rich.id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 794616 UNION 
select rich.id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 803171 UNION 
select rich.id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 803220 UNION 
select rich.id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 663162 UNION 
select rich.id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 665158 UNION 
select rich.id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 667788 UNION 
select rich.id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 667884 UNION 
select rich.id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 664924 UNION 
select rich.id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 667842 UNION 
select rich.id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 667747 UNION 
select rich.id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 667786 UNION 
select rich.id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 667814 UNION 
select rich.id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 667806 UNION 
select rich.id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 667710 UNION 
select rich.id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 667690 UNION 
select rich.id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 667535 UNION 
select rich.id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 660122 UNION 
select rich.id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 666071 UNION 
select rich.id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 665114 UNION 
select rich.id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 667637 UNION 
select rich.id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 661623 UNION 
select rich.id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 667503 UNION 
select rich.id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 667330 UNION 
select rich.id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 664484 UNION 
select rich.id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 667492 UNION 
select rich.id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 664323 UNION 
select rich.id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 665136 UNION 
select rich.id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 667746 UNION 
select rich.id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 351629 UNION 
select rich.id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 351687 UNION 
select rich.id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 351596 UNION 
select rich.id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 351521 UNION 
select rich.id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 351592 UNION 
select rich.id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 357754 UNION 
select rich.id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 406511 UNION 
select rich.id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 351694 UNION 
select rich.id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 406656 UNION 
select rich.id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 406445 UNION 
select rich.id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 406667 UNION 
select rich.id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 351714 UNION 
select rich.id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 398302 UNION 
select rich.id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 402031 UNION 
select rich.id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 380471 UNION 
select rich.id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 351543 UNION 
select rich.id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 362502 UNION 
select rich.id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 351650 UNION 
select rich.id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 357771 UNION 
select rich.id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 351612 UNION 
select rich.id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 362010 UNION 
select rich.id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 351468 UNION 
select rich.id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 351501 UNION 
select rich.id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 406592 UNION 
select rich.id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 406462;

select rich.id, rich.procedura_id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 616784 and rich.procedura_id = 3 UNION
select rich.id, rich.procedura_id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 274804 and rich.procedura_id = 3 UNION
select rich.id, rich.procedura_id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 633362 and rich.procedura_id = 3 UNION
select rich.id, rich.procedura_id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 642314 and rich.procedura_id = 3 UNION
select rich.id, rich.procedura_id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 403860 and rich.procedura_id = 3 UNION
select rich.id, rich.procedura_id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 526228 and rich.procedura_id = 3 UNION
select rich.id, rich.procedura_id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 453783 and rich.procedura_id = 3 UNION
select rich.id, rich.procedura_id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 642326 and rich.procedura_id = 3 UNION
select rich.id, rich.procedura_id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 394456 and rich.procedura_id = 3 UNION
select rich.id, rich.procedura_id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 485088 and rich.procedura_id = 3 UNION
select rich.id, rich.procedura_id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 642817 and rich.procedura_id = 3 UNION
select rich.id, rich.procedura_id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 269173 and rich.procedura_id = 3 UNION
select rich.id, rich.procedura_id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 634318 and rich.procedura_id = 3 UNION
select rich.id, rich.procedura_id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 269201 and rich.procedura_id = 3 UNION
select rich.id, rich.procedura_id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 269066 and rich.procedura_id = 3 UNION
select rich.id, rich.procedura_id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 642217 and rich.procedura_id = 3 UNION
select rich.id, rich.procedura_id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 269159 and rich.procedura_id = 3 UNION
select rich.id, rich.procedura_id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 642241 and rich.procedura_id = 3 UNION
select rich.id, rich.procedura_id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 421674 and rich.procedura_id = 3 UNION
select rich.id, rich.procedura_id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 269251 and rich.procedura_id = 3 UNION
select rich.id, rich.procedura_id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 279563 and rich.procedura_id = 3 UNION
select rich.id, rich.procedura_id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 642280 and rich.procedura_id = 3 UNION
select rich.id, rich.procedura_id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 634306 and rich.procedura_id = 3 UNION
select rich.id, rich.procedura_id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 642152 and rich.procedura_id = 3 UNION
select rich.id, rich.procedura_id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 446209 and rich.procedura_id = 3 UNION
select rich.id, rich.procedura_id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 642155 and rich.procedura_id = 3 UNION
select rich.id, rich.procedura_id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 380836 and rich.procedura_id = 3 UNION
select rich.id, rich.procedura_id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 642150 and rich.procedura_id = 3 UNION
select rich.id, rich.procedura_id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 565525 and rich.procedura_id = 3 UNION
select rich.id, rich.procedura_id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 269064 and rich.procedura_id = 3 UNION
select rich.id, rich.procedura_id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 642086 and rich.procedura_id = 3 UNION
select rich.id, rich.procedura_id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 561012 and rich.procedura_id = 3 UNION
select rich.id, rich.procedura_id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 566348 and rich.procedura_id = 3 UNION
select rich.id, rich.procedura_id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 633212 and rich.procedura_id = 3 UNION
select rich.id, rich.procedura_id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 642071 and rich.procedura_id = 3 UNION
select rich.id, rich.procedura_id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 633371 and rich.procedura_id = 3 UNION
select rich.id, rich.procedura_id from richieste rich join richieste_protocollo prot on prot.richiesta_id = rich.id where prot.num_pg = 635111 and rich.procedura_id = 3;

INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL, 2772);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL, 2800);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL, 2793);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL, 3067);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL, 2909);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL, 2778);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL, 2847);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL, 2939);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL, 2818);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL, 1325);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL, 1317);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL, 1397);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL, 1420);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL, 1373);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL, 1024);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL, 1312);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL, 1430);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL, 1274);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL, 1408);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL, 1336);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL, 1395);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL, 1398);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL, 977);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL, 1330);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL, 1324);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL, 1403);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL, 1301);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL, 1421);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL, 1164);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL, 1255);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL, 1309);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL, 1232);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL, 1354);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL, 1393);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL, 3193);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL, 3179);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL, 3236);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL, 3196);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL, 3192);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL, 3302);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL, 3841);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL, 3267);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL, 3776);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL, 3768);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL, 3878);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL, 3273);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL, 3739);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL, 3729);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL, 3447);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL, 3178);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL, 3256);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL, 3211);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL, 3213);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL, 3207);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL, 3314);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL, 3190);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL, 3195);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL, 3254);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL, 3760);


INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL,1036);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL,356);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL,1003);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL,715);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL,656);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL,788);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL,687);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL,1259);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL,677);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL,763);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL,1254);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL,18);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL,1143);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL,169);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL,4);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL,1122);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL,50);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL,1107);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL,430);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL,182);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL,363);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL,969);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL,1073);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL,1206);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL,650);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL,1197);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL,670);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL,1214);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL,905);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL,1);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL,1158);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL,844);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL,753);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL,1118);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL,1108);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL,974);
INSERT INTO `controlli_progetti` (`id`,  `esito`, `note`, `data_esito`, `data_cancellazione`, `data_creazione`, `data_modifica`, `creato_da`, `modificato_da`, `data_inizio_controlli`, `richiesta_id`) VALUES (NULL, NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL,1099);
