<?php

namespace RichiesteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FornitoreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FornitoreRepository extends EntityRepository
{
}
