<?php

namespace RichiesteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * IstruttoriaRichiestaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IstruttoriaRichiestaRepository extends EntityRepository
{
}
