<?php

namespace RichiesteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ServizioFornitoreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServizioFornitoreRepository extends EntityRepository
{
}
