<?php

namespace RichiesteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TipologiaServizioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipologiaServizioRepository extends EntityRepository
{
}
