<?php

namespace RichiesteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TipologiaFornitoreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipologiaFornitoreRepository extends EntityRepository
{
}
