<?php

namespace ProtocollazioneBundle\Repository;

/**
 * FascicoloBandoAziendaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FascicoloBandoAziendaRepository extends \Doctrine\ORM\EntityRepository
{
}
