<?php

namespace ProtocollazioneBundle\Repository;

/**
 * IstanzaProcessoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IstanzaProcessoRepository extends \Doctrine\ORM\EntityRepository
{
    public function cercaIstanzeByProcessoId($processo_id)
    {
        $query = $this->getEntityManager()
            ->createQuery(                    
                'SELECT ip 
                 FROM ProtocollazioneBundle:IstanzaProcesso ip 
                 WHERE ip.processo = :processo AND
                       ip.data_avvio is not null AND
                       ip.data_fine is null'
            )
            ->setParameter('processo', $processo_id);
        $result = $query->getResult();
        
        return $result;
    }
    
}
