<?php

namespace ProtocollazioneBundle\Repository;

/**
 * ProcessoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProcessoRepository extends \Doctrine\ORM\EntityRepository
{
}
