<?php

namespace ProtocollazioneBundle\Repository;

use ProtocollazioneBundle\Entity\RichiestaProtocolloFinanziamento;


/**
 * RichiestaProtocolloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RichiestaProtocolloFinanziamentoRepository extends \Doctrine\ORM\EntityRepository
{
    public function hasProtocolloSimile(RichiestaProtocolloFinanziamento $protocollo)
    {
       $dql = "SELECT 1
            FROM ProtocollazioneBundle:RichiestaProtocolloFinanziamento AS protocollo
            JOIN protocollo.richiesta AS richiesta
            WHERE protocollo.registro_pg = :registro_pg
            AND protocollo.anno_pg = :anno_pg
            AND protocollo.num_pg = :num_pg
            AND protocollo.richiesta <> :richiesta";

        $res = $this->getEntityManager()->createQuery($dql)
            ->setMaxResults(1)
            ->setParameters(array(
                'registro_pg' => $protocollo->getRegistroPg(),
                'anno_pg' => $protocollo->getAnnoPg(),
                'num_pg' => $protocollo->getNumPg(),
                'richiesta' => $protocollo->getRichiesta(),
            ))->getOneOrNullResult();

        return true == $res;
    }
}
