<?php

namespace ProtocollazioneBundle\Repository;

/**
 * RichiestaProtocolloDocumentoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RichiestaProtocolloDocumentoRepository extends \Doctrine\ORM\EntityRepository
{
    public function cercaFaseByProcessoId($processo_id)
    {
        $query = $this->getEntityManager()
            ->createQuery(                    
                'SELECT rpd 
                 FROM ProtocollazioneBundle:RichiestaProtocolloDocumento rpd
                 JOIN rpd.richiesta_protocollo rp WITH rp.processo = :processo AND rp.fase <> 0
                 WHERE rpd.principale = 1'
            )
            ->setParameter('processo', $processo_id);
        
        $result = $query->getResult();
        
        return $result;
    }

    public function contaRichiestePerProcesso() {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT p.id, p.codice, p.descrizione, count(p.id) as tot, rp.id as ricId
                 FROM ProtocollazioneBundle:RichiestaProtocollo rp
                 JOIN rp.processo p
                 WHERE rp.fase is NULL OR rp.fase <> 0
                 GROUP BY p.id, p.codice'
            );
           
        $result = $query->getScalarResult();
        
        return $result;
    }
}
