imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        #main:
        #    type:   stream
        #    path:   "%kernel.logs_dir%/%kernel.environment%.log"
        #    level:  debug
        #    formatter: monolog.formatter.standard
        console:
            type:   console
            bubble: false
            verbosity_levels:
                VERBOSITY_VERBOSE: INFO
                VERBOSITY_VERY_VERBOSE: DEBUG
            channels: ["!doctrine"]
        console_very_verbose:
            type:   console
            bubble: false
            verbosity_levels:
                VERBOSITY_VERBOSE: NOTICE
                VERBOSITY_VERY_VERBOSE: NOTICE
                VERBOSITY_DEBUG: DEBUG
            channels: ["doctrine"]
        gelf:
            type: service
            id: gelf.handler.log
            channels: ["schema31"]

        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type:   firephp
        #    level:  info
        #chromephp:
        #    type:   chromephp
        #    level:  info

#swiftmailer:
#    delivery_address: me@example.com
performer_pay_er:
    codice_portale: 'SFINGE_2020'
    iv: 'jd4ft2OI'
    key: 'pm0g5nXKqsMtnNtsxm4Wfh44'
    ebollo:
        codice_servizio: 'SERV_SFINGE'
        url_acquisto_carrello_mbd: 'https://payerbollostaging.lepida.net/ebollo/api/v1/AcquistoCarrelloMbd'
        url_invio_carrello_mbd: 'https://payerbollostaging.lepida.net/ebollo/api/v1/InvioCarrelloMbd'
        url_esito_carrello_mbd: 'https://payerbollostaging.lepida.net/ebollo/api/v1/EsitoCarrelloMbd'