<?php

namespace SoggettoBundle\Form;

use SfingeBundle\Entity\ComuneUnioniComuni;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ComuneUnioneType extends SoggettoType {

    public function __construct() {
        parent::__construct();
    }

	public function buildForm(FormBuilderInterface $builder, array $options) {

		parent::buildForm($builder, $options);

		$read_only = $options["readonly"];
		$disabled = $options["readonly"];

		if ($read_only == true) {
			$attr = array('readonly' => 'readonly');
		} else {
			$attr = array();
		}

		$builder->remove('data_costituzione');
		$builder->remove('dimensione');
		$builder->remove('dimensione_impresa');
		$builder->remove('stato');
		$builder->remove('provinciaEstera');
		$builder->remove('comuneEstero');
		$builder->remove('denominazione');
		//$builder->remove('provincia');
		//$builder->remove('comune');

        $builder->add('denominazione', self::hidden, array('data' => 'default',));

		$builder->add('comune_unione_comune', self::entity, array('required' => true,
			'disabled' => $disabled,
			'label' => 'Comune o Unione di comuni',
			'attr' => $attr,
			'class'=>"SfingeBundle\Entity\ComuneUnioniComuni",
			'placeholder'=>"Selezionare un comune o un unione di comuni",
			'choice_label'=>"descrizione"));
	}

    /**
     * @param FormView      $view
     * @param FormInterface $form
     * @param array         $options
     */
    public function finishView(FormView $view, FormInterface $form, array $options)
    {
        parent::finishView($view, $form, $options); // TODO: Change the autogenerated stub

        usort($view->children['comune_unione_comune']->vars['choices'], function ($first, $second){
            /** @var ComuneUnioniComuni $primo */
            $primo = $first->data;

            /** @var ComuneUnioniComuni $secondo */
            $secondo = $second->data;

            return $primo->getDescrizione() > $secondo->getDescrizione() ? 1 : -1;
        });
    }

	public function configureOptions(OptionsResolver $resolver) {
		$resolver->setDefaults(
				[
					'data_class' => 'SoggettoBundle\Entity\ComuneUnione',
					'readonly' => false,
					'validation_groups' => function($form){
		            	$data = $form->getData();
		                if(is_object($data->getStato())){
		                	if($data->getStato()->getDenominazione() == 'Italia'){
			                    return array("Default", "statoItalia");
			                }else{
			                    return array("Default");
			                }	
		                }else{
		                    return array("Default");
		                }
		            },
                    'em' => null,
                    'dataIndirizzo' => null,
		]);
		$resolver->setRequired("readonly");
		$resolver->setRequired("url_indietro");
        $resolver->setRequired("tipo");
	}

}
