<?php

namespace AttuazioneControlloBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DocumentoVariazioneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentoVariazioneRepository extends EntityRepository
{

	public function findDocumentiCaricati($id_variazione)
	{	
		
		$dql = "SELECT dp  FROM AttuazioneControlloBundle:DocumentoVariazione dp 
							JOIN dp.documento_file doc
							WHERE dp.variazione = :id_variazione";

		$q = $this->getEntityManager()->createQuery();
        $q->setDQL($dql);
        $q->setParameter("id_variazione", $id_variazione);
		
		$res = $q->getResult();
		
		return $res;
	}

}
