<?php

namespace SoggettoBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Exception;
use function is_null;

/**
 * AtecoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AtecoRepository extends EntityRepository
{
    /**
     * @param $param
     *
     * @return array
     */
	public function ricercaByCodiceDescrizione($param)
	{
		$q = $this->getEntityManager()
			->createQuery("SELECT a FROM SoggettoBundle:Ateco a WHERE a.codice LIKE :param OR a.descrizione LIKE :param ORDER BY a.codice")
            ->setParameter('param', '%' . $param . '%');
		return $q->getResult();
	}

    /**
     * @param $codice
     * @param $descrizione
     *
     * @return mixed
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
	public function ricercaByCodiceAndDescrizione($codice, $descrizione)
    {
        $descr = strtolower(str_replace('U\'','ù',str_replace('O\'','ò',str_replace('I\'','ì',str_replace('E\'','è', str_replace('A\'', 'à', $descrizione))))));

        $q = $this->getEntityManager()
            ->createQuery("SELECT a FROM SoggettoBundle:Ateco a WHERE a.codice LIKE :codice OR a.descrizione LIKE :descrizione ORDER BY a.codice")
            ->setParameter('codice', '%' . $codice . '%')
            ->setParameter('descrizione', '%' . $descr . '%')
            ->setMaxResults(1)
            ->getOneOrNullResult();
        return $q;
    }

    public function getCodiceAteco()
	{
		$q = $this->getEntityManager()
			->createQuery("SELECT a FROM SoggettoBundle:Ateco a ORDER BY a.codice");
		return $q->getResult();
	}
	
	
	public function ricercaAtecoCipeCup(
										$sezione,
										$divisione,
										$gruppo,
										$classe,
										$categoria=null,
										$sottocategoria=null
										) {
		try {
			
			/*
			 * $ateco_gruppo			= substr($Ateco->getCodice(), 1, 4);
			$ateco_classe			= substr($Ateco->getCodice(), 1, 6);
			$ateco_categoria		= substr($Ateco->getCodice(), 1, 7);
			 */
			$query = "SELECT a "
					."FROM SoggettoBundle:Ateco a "
					."WHERE "
					."a.codice_macro_settore='$sezione' AND "
					."a.codice_area='$divisione' AND "
					."SUBSTRING(a.codice, 1,4)='$gruppo' AND "
					."SUBSTRING(a.codice, 1,5)='$classe' ";
			
			if(!is_null($categoria)) $query .=" AND SUBSTRING(a.codice,1,7)='$categoria '";
			if(!is_null($sottocategoria)) $query .=" AND a.codice='$sottocategoria '";

			$q = $this->getEntityManager()->createQuery($query);
			$sql = $q->getSQL();
			$results = $q->getResult();

			if(is_null($results) || count($results) ==0) return false;
			return true;
		} catch (Exception $ex) {
			throw new Exception("errore generico durante il controllo dei codici ateco", 0, $ex);
		}
				 
	}
}