<?php

namespace CertificazioniBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TipologiaCertificazioneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipologiaCertificazioneRepository extends EntityRepository
{
}
