<?php

namespace SfingeBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;


/**
 * DocumentiOOII
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentiOOIIRepository extends EntityRepository {

	public function findDocumentiCaricati($id_organismo_intermedio)
	{	
		
		$dql = "SELECT dr  FROM SfingeBundle:DocumentiOOII dr 
							JOIN dr.documento_file doc
							WHERE dr.organismo_intermedio = :id_organismo_intermedio";

		$q = $this->getEntityManager()->createQuery();
        $q->setDQL($dql);
        $q->setParameter("id_organismo_intermedio", $id_organismo_intermedio);
		
		$res = $q->getResult();
		
		return $res;
	}	
	
}
