<?php

namespace IstruttorieBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DocumentoIstruttoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentoIstruttoriaRepository extends EntityRepository
{
}
