<?php

namespace AttuazioneControlloBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EconomiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EconomiaRepository extends EntityRepository {
    
}
