services:
  #    performer_pay_er.example:
  #        class: Performer\PayERBundle\Example
  #        arguments: ["@service_id", "plain_value", "%parameter%"]

  Performer\PayERBundle\Service\PayERInterface:
    class: Performer\PayERBundle\Service\PayER
    arguments: [null, null, null]

  Performer\PayERBundle\Service\EBolloInterface:
    class: Performer\PayERBundle\Service\EBollo
    arguments: [null, null, null, null, null, '@router', '@Performer\PayERBundle\Service\PayERInterface', '@doctrine.orm.entity_manager', '@event_dispatcher']

  performer_payer_ebollo:
    alias: Performer\PayERBundle\Service\EBolloInterface
